import type { ServiceQuestion } from '../types'

export const homepageQuestions: ServiceQuestion[] = [
  {
    id: 1,
    title: 'どのようなホームページを作りたいですか？',
    subtitle: '大まかなイメージで構いません',
    type: 'textarea',
    field: 'projectOverview',
    placeholder: '例: 美容室のホームページをリニューアルしたい、新規オープンの飲食店のサイトを作りたい、など',
    maxLength: 500,
    required: true,
  },
  {
    id: 2,
    title: 'お客様の業種を教えてください',
    subtitle: '最も近いものをお選びください',
    type: 'button-grid',
    field: 'industry',
    options: [
      '飲食店',
      '美容・サロン',
      '医療・クリニック',
      '士業（弁護士・税理士等）',
      '不動産',
      '小売・EC',
      '製造業',
      '教育・スクール',
      'その他',
    ],
    required: true,
  },
  {
    id: 3,
    title: '必要な機能を選んでください',
    subtitle: '複数選択可能です',
    type: 'checkbox',
    field: 'features',
    options: [
      'お問い合わせフォーム',
      '予約システム',
      'ブログ・お知らせ',
      'SNS連携',
      '写真ギャラリー',
      'Googleマップ埋め込み',
      '多言語対応',
      'EC機能（商品販売）',
      'スタッフ紹介',
      '求人ページ',
    ],
    required: true,
  },
  {
    id: 4,
    title: 'ホームページの更新はどのようにしたいですか？',
    subtitle: '運用方法をお選びください',
    type: 'button-grid',
    field: 'updateMethod',
    options: ['自分で更新したい（CMS）', '更新は依頼したい', 'まだ決めていない'],
    required: true,
  },
  {
    id: 5,
    title: '希望の公開時期を教えてください',
    subtitle: 'おおよその目安で構いません',
    type: 'button-grid',
    field: 'timeline',
    options: ['1ヶ月以内', '2〜3ヶ月', '3〜6ヶ月', '未定'],
    required: true,
  },
  {
    id: 6,
    title: 'ご予算の目安を教えてください',
    subtitle: 'お気軽にお選びください',
    type: 'button-grid',
    field: 'budget',
    options: ['30万円以下', '30〜50万円', '50〜100万円', '100〜300万円', '300万円以上', '未定'],
    required: true,
  },
]
