import type { ServiceQuestion } from '../types'

export const aiIntegrationQuestions: ServiceQuestion[] = [
  {
    id: 1,
    title: 'AIをどのように活用したいですか？',
    subtitle: '最も近いものをお選びください',
    type: 'button-grid',
    field: 'aiUseCase',
    options: [
      'チャットボット・問い合わせ対応',
      '文書作成・要約の自動化',
      '画像・動画の生成・解析',
      'データ分析・予測',
      '業務プロセスの自動化',
      'その他・まだ具体的でない',
    ],
    required: true,
  },
  {
    id: 2,
    title: 'お客様の業種を教えてください',
    subtitle: '最も近いものをお選びください',
    type: 'button-grid',
    field: 'industry',
    options: [
      '製造業',
      'IT・通信',
      '金融・保険',
      '小売・EC',
      '医療・ヘルスケア',
      '教育',
      '不動産',
      'メディア・広告',
      'その他',
    ],
    required: true,
  },
  {
    id: 3,
    title: 'AI処理するデータの規模はどの程度ですか？',
    subtitle: 'おおよその目安で構いません',
    type: 'button-grid',
    field: 'dataScale',
    options: [
      '少量（数百件/月）',
      '中量（数千件/月）',
      '大量（数万件以上/月）',
      'まだわからない',
    ],
    required: true,
  },
  {
    id: 4,
    title: '連携が必要な既存システムはありますか？',
    subtitle: '複数選択可能です',
    type: 'checkbox',
    field: 'existingSystems',
    options: [
      'Webサイト・ECサイト',
      'CRM（Salesforce等）',
      'チャットツール（Slack・Teams等）',
      '社内データベース',
      'クラウドストレージ',
      'ERPシステム',
      '特になし',
    ],
    required: true,
  },
  {
    id: 5,
    title: '導入の希望時期を教えてください',
    subtitle: 'おおよその目安で構いません',
    type: 'button-grid',
    field: 'timeline',
    options: ['1ヶ月以内', '2〜3ヶ月', '4〜6ヶ月', '6ヶ月以上', '未定'],
    required: true,
  },
  {
    id: 6,
    title: 'ご予算の目安を教えてください',
    subtitle: 'お気軽にお選びください',
    type: 'button-grid',
    field: 'budget',
    options: ['50万円以下', '50〜100万円', '100〜300万円', '300〜500万円', '500万円以上', '未定'],
    required: true,
  },
]
