# Generated by Django 5.0.6 on 2025-12-28 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RAGDataStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50, verbose_name='ソース種別')),
                ('stat_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='統計日')),
                ('total_vectors', models.IntegerField(default=0, verbose_name='総ベクトル数')),
                ('total_searches', models.IntegerField(default=0, verbose_name='総検索回数')),
                ('avg_similarity', models.FloatField(default=0.0, verbose_name='平均類似度')),
                ('avg_duration_ms', models.FloatField(default=0.0, verbose_name='平均検索時間(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'RAGデータ統計',
                'verbose_name_plural': 'RAGデータ統計',
                'db_table': 'rag_data_statistics',
                'ordering': ['-stat_date'],
                'unique_together': {('source_type', 'stat_date')},
            },
        ),
        migrations.CreateModel(
            name='RAGSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='検索クエリ')),
                ('sources', models.JSONField(default=list, verbose_name='検索ソース')),
                ('results_count', models.IntegerField(default=0, verbose_name='結果件数')),
                ('top_similarity', models.FloatField(blank=True, null=True, verbose_name='最高類似度')),
                ('avg_similarity', models.FloatField(blank=True, null=True, verbose_name='平均類似度')),
                ('search_duration_ms', models.IntegerField(blank=True, null=True, verbose_name='検索時間(ms)')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日時')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'RAG検索ログ',
                'verbose_name_plural': 'RAG検索ログ',
                'db_table': 'rag_search_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='rag_search__created_818daf_idx'), models.Index(fields=['query'], name='rag_search__query_69d472_idx')],
            },
        ),
    ]
