# Generated by Django 5.0.6 on 2025-12-28 20:44

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='検索クエリ')),
                ('expected_fragment_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='正解として期待されるFragment IDのリスト', size=None, verbose_name='正解のFragment ID')),
                ('category', models.CharField(help_text='author, technical, general等', max_length=50, verbose_name='カテゴリ')),
                ('difficulty', models.IntegerField(default=1, help_text='1（簡単）〜5（難しい）', verbose_name='難易度')),
                ('description', models.TextField(blank=True, help_text='このクエリの目的や期待される結果の説明', verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '評価クエリ',
                'verbose_name_plural': '評価クエリ',
                'db_table': 'evaluation_queries',
                'ordering': ['category', 'difficulty', 'id'],
                'indexes': [models.Index(fields=['category'], name='evaluation__categor_80b002_idx'), models.Index(fields=['difficulty'], name='evaluation__difficu_2e4f35_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(help_text='baseline, bm25, optimized等', max_length=50, verbose_name='バリアント')),
                ('precision_at_5', models.FloatField(blank=True, help_text='上位5件の精度（0.0〜1.0）', null=True, verbose_name='Precision@5')),
                ('mrr', models.FloatField(blank=True, help_text='Mean Reciprocal Rank（0.0〜1.0）', null=True, verbose_name='MRR')),
                ('ndcg', models.FloatField(blank=True, help_text='Normalized Discounted Cumulative Gain（0.0〜1.0）', null=True, verbose_name='NDCG')),
                ('search_duration_ms', models.IntegerField(blank=True, null=True, verbose_name='検索時間(ms)')),
                ('results_json', models.JSONField(blank=True, help_text='検索結果の詳細（デバッグ用）', null=True, verbose_name='検索結果詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='rag_api.evaluationquery', verbose_name='評価クエリ')),
            ],
            options={
                'verbose_name': '評価結果',
                'verbose_name_plural': '評価結果',
                'db_table': 'evaluation_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['variant'], name='evaluation__variant_fec46d_idx'), models.Index(fields=['-created_at'], name='evaluation__created_84139b_idx'), models.Index(fields=['query', 'variant'], name='evaluation__query_i_51e8e7_idx')],
            },
        ),
    ]
