# Generated by Django 5.0.6 on 2025-12-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0003_evaluationresult_dataset_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresult',
            name='recall_at_20',
            field=models.FloatField(blank=True, help_text='上位20件の網羅性（0.0〜1.0）', null=True, verbose_name='Recall@20'),
        ),
    ]
