# Generated by Django 5.0.6 on 2026-01-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_api', '0004_add_recall_at_20'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresult',
            name='mlflow_run_id',
            field=models.CharField(blank=True, help_text='MLflow Tracking Server上のrun_id（相互参照用）', max_length=64, null=True, verbose_name='MLflow Run ID'),
        ),
    ]
