import type { ServiceQuestion } from '../types'

export const efficiencyQuestions: ServiceQuestion[] = [
  {
    id: 1,
    title: '現在、最も課題を感じている業務は何ですか？',
    subtitle: '大まかなイメージで構いません',
    type: 'textarea',
    field: 'projectOverview',
    placeholder: '例: 月末の経費精算に丸2日かかる、顧客データが複数のExcelに散在している、など',
    maxLength: 500,
    required: true,
  },
  {
    id: 2,
    title: '組織の従業員規模を教えてください',
    subtitle: 'システムを利用する組織の規模',
    type: 'button-grid',
    field: 'employeeCount',
    options: ['1-10名', '11-50名', '51-100名', '101-300名', '300名以上'],
    required: true,
  },
  {
    id: 3,
    title: '現在使用しているツールを教えてください',
    subtitle: '複数選択可能です',
    type: 'checkbox',
    field: 'existingTools',
    options: [
      'Excel / スプレッドシート',
      'kintone',
      'Salesforce',
      'freee / マネーフォワード',
      'Slack / Teams',
      'Google Workspace',
      'Microsoft 365',
      '紙・手作業',
      'その他の業務システム',
    ],
    required: true,
  },
  {
    id: 4,
    title: '自動化・効率化したい業務を選んでください',
    subtitle: '複数選択可能です',
    type: 'checkbox',
    field: 'automationTargets',
    options: [
      '経費精算・請求書処理',
      '顧客管理（CRM）',
      '在庫管理',
      '勤怠管理',
      'ワークフロー承認',
      'レポート・帳票作成',
      '受発注管理',
      'データ入力・転記',
      'メール・通知の自動化',
      'その他',
    ],
    required: true,
  },
  {
    id: 5,
    title: 'モバイルでの利用は必要ですか？',
    subtitle: '外出先やスマホからのアクセス',
    type: 'button-grid',
    field: 'mobileNeeded',
    options: ['必須', 'あると嬉しい', '不要', '未定'],
    required: true,
  },
  {
    id: 6,
    title: '導入の希望時期を教えてください',
    subtitle: 'おおよその目安で構いません',
    type: 'button-grid',
    field: 'timeline',
    options: ['1ヶ月以内', '2〜3ヶ月', '4〜6ヶ月', '6ヶ月以上', '未定'],
    required: true,
  },
  {
    id: 7,
    title: 'ご予算の目安を教えてください',
    subtitle: 'お気軽にお選びください',
    type: 'button-grid',
    field: 'budget',
    options: ['50万円以下', '50〜100万円', '100〜300万円', '300〜500万円', '500万円以上', '未定'],
    required: true,
  },
]
