apiVersion: 1

datasources:
  - name: Supabase PostgreSQL
    type: postgres
    access: proxy
    url: db.xhmhzhethpwjxuwksmuv.supabase.co:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: ${DATABASE_PASSWORD}
    jsonData:
      sslmode: require
      postgresVersion: 1500
      timescaledb: false
    editable: true
    isDefault: true

